language: node_js
sudo: false
node_js:
  - 10
branches:
  only:
  - master
  - develop
  - /^release-.*$/
  - /^feature/dev-.*$/

services:
  - rabbitmq
  - redis-server
  - mysql-percona
  
install:
  - npm install

script:
  - npm test

env:
  - NODE_ENV=TEST